### ISSUE TITLE
Ambiguous Error Message in Experiment File Loading

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/hutch-python#125]
Ran into this issue that was slightly confusing. I figured it out quickly but I think a novice might be overwhelmed. If your experiment file raises an `ImportError` when it is loaded the error message generated claims that the experiment file is missing. It would be nice to disambiguate between the two cases; there is no experiment file, and you gave me an experiment file that raises an `ImportError`. 

https://github.com/pcdshub/hutch-python/blob/695c6b75e1b8ecda4a32bccb66d3311363fa6532/hutch_python/exp_load.py#L34-L38

**Comment by teddyrendahl** [comment]
Could always just do an `os.path.exists` before you try and import.

**Comment by ZLLentz** [comment]
Seems awkard to do that because this file doesn't know anything about the directory structure

**Comment by teddyrendahl** [comment]
Ah I see.
