### ISSUE TITLE
Hutch-python Engineering Mode

### ISSUE THREAD

**Issue by ZryletTC** [pcdshub/hutch-python#188]
So, in general, engineering mode is on by default, which makes sense.

However, for hutch-python, since it is often run by scientists and users, should we turn engineering mode off, so that the tab-complete is more manageable for them? We can always turn it back on when we want to.

Thoughts? @ZLLentz @silkenelson @rajanplumley

**Comment by rajanplumley** [comment]
IMO it should be off by default and enabled when needed.

**Comment by ZLLentz** [comment]
Suggested implementation:
- turn it off in `cli.main` where the debugging tools are defined
- pull `set_engineering_mode` into the default namespace the same way the debugging tools are
