### ISSUE TITLE
More Dramatic Failure for Beamline and Experiment Files

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/hutch-python#192]
## Expected Behavior

The user should be very aware if their user-defined files (beamline, experiment, etc.) failed to load and why they failed to load, and that any devices defined within them will be unavailable.

## Current Behavior

The  beamline file can claim that all of its contents succeeded, but then fail at the end with just a small red line in the load sequence. Then, all the items that claimed success are actually missing!

## Possible Solution

When files to load from are provided but raise exceptions in their loading, we should either:
1. Show an error message with the traceback, but continue loading
2. Show an error message with the traceback, and quit execution

I don't believe it is possible to do a partial load of these user files.

**Comment by klauer** [comment]
Spent a bit of time looking into partial loading of beamline files. While it may technically be possible to hack something together to grab the devices that succeeded in loading, I think the "possible solutions" of the issue are more appropriate, as we have no way of knowing what failed to load after the first exception.

To that end, we should probably implement both along the lines of: 

`Failed to load your custom config! See traceback above. Continue? [Yn]`

**Comment by ZLLentz** [comment]
I have to say I'm a bit curious about partial loading- but I assume we'd have to structure our beamline files in very specific ways to make that a reality.

I like the idea of asking for continuation.
