### ISSUE TITLE
Docs are Busted

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/hutch-python#194]
This is failing the whole travis on the tag and preventing an anaconda upload

**Comment by klauer** [comment]
Argh https://travis-ci.org/github/pcdshub/hutch-python/jobs/689775454

**Comment by ZLLentz** [comment]
I'm not able to reproduce this locally. I'm going to try re-running the tag...

**Comment by klauer** [comment]
Hmm, the error looks like bluesky/device/pcdsdevices related or something, but I'd expect that to fail locally as well for you.

You have sphinx 3? It was just released, I believe.

**Comment by ZLLentz** [comment]
Yes, I have sphinx 3. When this fails again I'll follow along with the travis build to replicate the environment package-for-package

**Comment by ZLLentz** [comment]
closed in #195
