### ISSUE TITLE
Guessing of ami-proxy broken with new config files

### ISSUE THREAD

**Issue by silkenelson** [pcdshub/hutch-python#196]
## Expected Behavior
I expect that the amiProxy shall be found/defined in my beam line python and that I thus can define AmiDets

## Current Behavior
get_ami_proxy in ext_scripts uses the old cnf file style where the host name was its IP address as a string - I think.
Now we use the netconfig entry instead.

## Steps to Reproduce (for bugs)
start XCS beamline python
from pcdsdaq.ami import AmiDet 
daq.configure(events=120)
det = AmiDet('ProcTime',name='ProcTime')  

## Context
I can't demonstrate the use of ami in my BlueSky plan demo.

## Your Environment
xcs3 started as xcsopr on xcs-daq

**Comment by ZLLentz** [comment]
Ah darn, you take a year off of doing science and everything changes!

**Comment by ZLLentz** [comment]
closed by https://github.com/pcdshub/pcdsdaq/pull/71
