### ISSUE TITLE
Lightpath Support

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/hutch-python#2]
- Read from the `cfg.yaml` file to determine which path to load

Example entry:
```
lightpath:
  - MFX
```

**Comment by ZLLentz** [comment]
We can get by without this for a while. For now, a `beamline` plugin will choose which `happi` objects to load. Later, we will consult `lightpath` to do this and also create a `LightController`.

**Comment by ZLLentz** [comment]
This is done

**Comment by teddyrendahl** [comment]
Closed via #60
