### ISSUE TITLE
Happi devices with negative z are ignored in load

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/hutch-python#247]
## Expected Behavior

Load all hutch devices

## Current Behavior

Loads only `z>=0`
https://github.com/pcdshub/hutch-python/blob/493565d1e3e007f3791921e8fe4b0bf31982968a/hutch_python/happi.py#L49-L50

## Possible Solution

Load everything? I probably want to discuss this with someone to make sure there isn't a good reason for this `z>=0` stipulation.

## Context

tmo lamp was at z=-1 and didn't load in tmo3

**Comment by klauer** [comment]
Maybe some used `z<0` to mean inactive at some point, or something? I don't see a good reason to carry forward this implementation detail.

**Comment by ZLLentz** [comment]
That's a reasonable assumption. Now we definitely have an `active` tag that should (is) used for this purpose.
