### ISSUE TITLE
Scientific formatting in table

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/hutch-python#260]
## Expected Behavior

User set thresholds for LiveTable values to be displayed as scientific notation

## Current Behavior

No scientific notation all the time

## Possible Solution

- Mess with the `LiveTable` hidden settings:
```
In [4]: from bluesky.callbacks.core import LiveTable
In [14]: LiveTable._FMT_MAP['number'] = 'g'
```
```
|       283 | 09:48:30.5 |      -4.35 |   7.63e-05 |
|       284 | 09:48:30.5 |      -4.33 |   8.33e-05 |
|       285 | 09:48:30.5 |      -4.31 |   9.08e-05 |
|       286 | 09:48:30.5 |      -4.29 |    9.9e-05 |
|       287 | 09:48:30.5 |      -4.27 |   0.000108 |
|       288 | 09:48:30.5 |      -4.25 |   0.000117 |
|       289 | 09:48:30.5 |      -4.23 |   0.000128 |
|       290 | 09:48:30.5 |      -4.21 |   0.000139 |
```
- Do something with variety metadata, e.g. make a new callback based on `LiveTable`

## Steps to Reproduce (for bugs)

1. Run a scan with very small or very big numbers

## Context

https://slac.slack.com/archives/C9RP2PQHM/p1612872334003200

## Your Environment

Latest

**Comment by klauer** [comment]
Related https://github.com/pcdshub/nabs/issues/20 (found it!)
