### ISSUE TITLE
BEC Not Easily Locatable in Namespace

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/hutch-python#261]
## Expected Behavior

I should be able to find the best-effort callback that the RunEngine is subscribed to and change the settings

## Current Behavior

I had to dig really deep to find our bec:
```
 next(RE.dispatcher.cb_registry.callbacks.values())[0][1].func
```
## Possible Solution

Just store it when we create it the same way we store the other run engine tools so it comes into the user namespace. Figure out the best place to put things like this, perhaps a config namespace?

## Context

Messing around in xpp's python session and needed this for some reason, I've already forgotten why

**Comment by ZryletTC** [comment]
YES please! I've dealt with this before and it is a pain... It should definitely be easily findable.
