### ISSUE TITLE
Experiment file seems to load based on current host not specified hutch

### ISSUE THREAD

**Issue by ZryletTC** [pcdshub/hutch-python#265]
## Expected Behavior
If I run xcs3 anywhere, it should load xcs's configuration.

## Current Behavior

It currently seems to load an experiment based on what machine you are currently running on regardless of which hutch-python instance is being run.

## Possible Solution

Looks like the API for get_curr_exp script in engineering_tools changed last year so a `-H` flag is now needed to specify hutch. I've tested with this simple change to the string in the constants file and it works. I'll put together a short PR soon.

## Steps to Reproduce (for bugs)

```
ssh xpp-control
xcs3
```
and look at which experiment is loaded

## Context
I'm in xpp and wanted to look at xcs...

## Your Environment
xpp-control

**Comment by silkenelson** [comment]
How did you get the experiment before? get_curr_exp will default to giving you the experiment the current hutch you are in unless you pass it an option - assuming your current host will allow a hutch-determination.

**Comment by ZryletTC** [comment]
It looks like that string was written back in 2018, one month before the -i and -H options were added. Before that you could just pass the hutch name as a singular positional argument.
