### ISSUE TITLE
Allow Plugins to request additional information

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/hutch-python#27]
## Expected Behavior

There may be use cases where there is information that is needed by multiple Plugins i.e experiment number. In the current schema, this info would have to be duplicated in the YAML file.

## Possible Solution

Add an extra class attribute to the `BasePlugin` called `extraneous`. This would point to other information in the YAML file that may not be underneath the Plugin explicitly. Then in `load_conf.py` the `extraneous` list is checked any additional information needed is added to the `info` dictionary directly.
 For example

### YAML file
```YAML
experiment_no : LJ001

happi:
         ...
```

### Happi Plugin
```python
class Plugin
     name = 'happi'
     extraneous = ['experiment_no']
```

**Comment by ZLLentz** [comment]
An even simpler implementation might be to not require an `extraneous` argument at all, and let all plugins reference the original yaml dictionary. Solid idea.
