### ISSUE TITLE
Use EpicsSignal.set_defaults to configure default timeouts

### ISSUE THREAD

**Issue by klauer** [pcdshub/hutch-python#273]
## Expected Behavior
Infinite timeouts are (arguably _!!_ ) a bad thing, and can potentially cause frequent "Another set() call is currently in progress" issues.

## Current Behavior
We don't set a timeout, and rely on ophyd to provide sane defaults.

## Possible Solution
Use `EpicsSignalBase.set_defaults` to configure the timeouts:
https://github.com/bluesky/ophyd/blob/c9f44e21ddd2b722a404bae4bce45d99b263c333/ophyd/signal.py#L828-L852

## Context
XCS had a very confusing timeout-related bug that took much too long to diagnose.

**Comment by ZLLentz** [comment]
I'm suggesting `5` as the default- long enough for processing, short enough so that you don't get impatient waiting for a failure.
