### ISSUE TITLE
IPython logging: post_execute -> pre_run_cell

### ISSUE THREAD

**Issue by klauer** [pcdshub/hutch-python#281]
https://github.com/pcdshub/hutch-python/blob/615b5a6804a7cf7002e3186c1e0500edbc938ead/hutch_python/ipython_log.py#L82

With `pre_execute` I believe our users' input stream will be logged in the correct order.
```
In [52]: ip.events.callbacks
Out[52]:
{'pre_execute': [<bound method InteractiveShell._clear_warning_registry of <IPython.terminal.interactiveshell.TerminalInteractiveShell object at 0x7efc92da0280>>],
 'pre_run_cell': [],
 'post_execute': [<bound method IPythonLogger.log of <hutch_python.ipython_log.IPythonLogger object at 0x7efc92da00d0>>],
 'post_run_cell': [],
 'shell_initialized': []}

```

**Comment by ZLLentz** [comment]
I think there also are some changes needed to the logging itself, which currently checks the `In` global which is (or at least used to be) only set after the command finished executing.

**Comment by klauer** [comment]
Yeah, you're right - upon further investigation, `In` isn't updated in `pre_execute`

`pre_run_cell` offers input information, and should be used here:

```
ip.events.register('pre_run_cell', callback)

def callback(info):
    info.raw_cell  # <-- has the input
```
