### ISSUE TITLE
pip requirements wrong

### ISSUE THREAD

**Issue by klauer** [pcdshub/hutch-python#284]
* We generally just install with conda, so this isn't critical
* However, the 3-line `requirements.txt` is _very_ out of date with respect to the conda recipe
https://github.com/pcdshub/hutch-python/blob/master/requirements.txt
https://github.com/pcdshub/hutch-python/blob/master/conda-recipe/meta.yaml

Handy pcdsutils requirements comparator:
```
$ requirements-compare hutch-python
--- requirements.txt: host/build/run ---
Missing in pip:
- archapp
- bluesky
- cookiecutter
- elog
- happi
- jinja2
- lightpath
- matplotlib
- nabs
- pcdscalc
- pcdsdaq
- pcdsdevices
- pcdsutils
- psdm_qs_cli
- pyfiglet
- pyqt5
- requests
- simplejson

--- dev-requirements.txt: test ---
Missing in conda:
- doctr
- flake8
- nbsphinx
- pytest
- pytest-timeout
- sphinx
- sphinx_rtd_theme

--- docs-requirements.txt: docs ---
```

**Comment by ZLLentz** [comment]
oops
