### ISSUE TITLE
User request: abort by default on ctrl+c of bluesky plan

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/hutch-python#306]
## Expected Behavior

XPP wants the ctrl+c out of a run to immediately abort since they don't make use of resume or setting abort reasons. They suggested an alternative keybind, ctrl+p to pause the run for possible resuming.

## Current Behavior

Default bluesky behavior, user has the opportunity to decide after ctrl+c how to resolve the situation via calling methods on the run engine

## Possible Solution

- Subclass RunEngine and extend `__call__`
- Start a background thread that listens for ctrl+p

## Context

XPP asked about this on the pcds-help slack channel
No jira request yet that I know about

**Comment by tangkong** [comment]
Closed by #324
