### ISSUE TITLE
Search by Device Type

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/hutch-python#34]
## Expected Behavior

I think it would be a neat feature to search the namespace by class. This could help operators find the devices they need / have available.

```python
find_my(pcdsdevices.device_types.PIM)
```

**Comment by ZLLentz** [comment]
I'm concerned about the cli ease of finding `pcdsdevices.device_types.PIM`, but solid idea. This can reuse some code from the `namespace` plugin.

**Comment by ZLLentz** [comment]
@teddyrendahl Is this closed by having the class namespace available as a function? Or more steps needed?

**Comment by teddyrendahl** [comment]
Closed by `class_namespace`!
