### ISSUE TITLE
Inclusion of preceding beamlines

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/hutch-python#69]
## Expected Behavior

Now that `lightpath` has a hardcoded configuration we can tell all the devices that need to be loaded quite easily. It would be nice if downstream beamlines are included as well, maybe contained within a namespace i.e
```python
mfx_dg1_pim
xrt.hxx_valve
```
## Current Behavior

Only devices on the beamline that match the hutch are included.

**Comment by ZLLentz** [comment]
If we do load these devices I expect the existing infrastructure to automatically create namespaces for them of the form `beamline.stand.name`... so for us, that's unfortunately `hxd.hxx.valve`, for example. We may need to rethink how we set these namespaces up.
