### ISSUE TITLE
Daq Map Incomplete

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/hutch-python#72]
## Expected Behavior

`daq` should work for all the hutches.

## Current Behavior

`daq` will not work outside of `mfx` because we haven't defined the platform args

## Possible Solution

Need to dig through the cnf files and pick out the platforms. We also need to think about what to do for the multidaq in `cxi`

**Comment by teddyrendahl** [comment]
We should ask Koglin how keeps track of daq modes. I think he has a way in his current setup scripts.

**Comment by ZLLentz** [comment]
I agree
